title: ICME Python Summer Workshop, 2023 edition
logo: /assets/img/logo.gif
description: July 24-25, 1-4 PM PT on Zoom https://stanford.zoom.us/j/99081966671?pwd=QitGZktCV2JQcSsvU284c3JlenY4UT09
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
